### PR TITLE
67 postcodes

### PR DESCRIPTION
**Pull request by ivanoblomov**
Closes: #67

 ## Goal
Change `CACLocation#zip` to prepend `=` so Google Sheets imports zip codes correctly.

 ## Notes
I couldn't do a full end-to-end test with `bundle ex rake export_cac_as_storepoint` because ArcGIS is currently returning null results:
```ruby
irb(main):003:0> require 'geoservices.rb'
=> true
irb(main):004:0> service = Geoservice::MapService.new(url: "https://services.arcgis.com/8ZpVMShClf8U8dae/ArcGIS/rest/services/TestingLocation
_public/FeatureServer")
irb(main):005:0> data = service.query(0)
irb(main):006:0> data
=> nil
```

### CODE REVIEW

**Comment by ivanoblomov** [comment]
Above bug is causing [these failures](https://github.com/Spark-Bio/covid-storepoint/pull/68/checks?check_run_id=644964929).

**Comment by ivanoblomov** [comment]
Above bug added as #69.

**Comment by neilberkman** [comment]
@ivanoblomov just prepending `=` may not be enough. The code currently generates triple quotes e.g. `"""01234"""`. We want to end up with `="01234"`.

**Comment by ivanoblomov** [comment]
@neilberkman this works as expected in Apple Numbers and Excel. Are you getting different results?

**Comment by ivanoblomov** [comment]
@neilberkman are we good with this PR?

**Pull request merged**
